### ISSUE TITLE
Make Run Error

### ISSUE THREAD

**Issue by kylemclaren** [adammeghji/ansible-ltc-mining-on-ec2#1]
Thanks for this repo, getting the following error when I run `make run`:

`ImportError: No module named yaml`
`make: *** [playbook] Error 1`

**Comment by adammeghji** [comment]
What OS are you on?

**Comment by adammeghji** [comment]
If you're on Ubuntu and don't have python installed yet, try this:

```
sudo apt-get install python-pip python-dev
sudo pip install paramiko PyYAML jinja2
```

That will install the dependencies required by ansible.

**Comment by kylemclaren** [comment]
I'm on Mac OS X...

**Comment by adammeghji** [comment]
You'll need pip, so try:

```
sudo easy_install pip
sudo pip install paramiko PyYAML jinja2
```

Does that do the trick?  If so, I'll amend the docs.

**Comment by kylemclaren** [comment]
OK definitely had pip..

Installed those dependencies so I will try again when I spin up another cluster (when/if the price goes down?)

For now I'll close and reopen if I have problems.
